name: TIL Template
description: TIL Template
title: "[WebArticle]: "
labels: ["engineering"]
assignees: 
  - yumechi
body:
  - type: input
    id: url-string
    attributes:
      label: "URL"
      description: "input URL"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: "所感"
      description: "input Details"
    validations:
      required: true
